# Generated by Django 5.1.2 on 2024-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='CGPA',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
