# Generated by Django 5.1.2 on 2024-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_resume_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='CGPA',
            field=models.FloatField(default=10, max_length=10),
        ),
    ]
