# Generated by Django 5.1.2 on 2024-11-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_alter_resume_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='CGPA',
            field=models.FloatField(default=7, max_length=10),
        ),
    ]
