# Generated by Django 5.1.2 on 2024-11-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_alter_resume_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
