# Generated by Django 5.1.2 on 2024-11-07 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0005_resume_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='CGPA',
            field=models.FloatField(default=7),
        ),
        migrations.AlterField(
            model_name='resume',
            name='score',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
