# Generated by Django 5.1.2 on 2024-11-07 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0007_alter_resume_cgpa_alter_resume_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
