# Generated by Django 5.1.2 on 2024-11-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0008_alter_resume_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='vedika',
            field=models.CharField(default='v', max_length=39),
        ),
    ]
