# Generated by Django 5.1.2 on 2024-11-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0009_resume_vedika'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='vedika',
        ),
    ]
